### PR TITLE
Exported source factory

### PR DESCRIPTION
**Pull request by Venipa**
#77

### CODE REVIEW

**Comment by odahcam** [comment]
Not sure if this is the best way to expose the class, but it is a very interesting idea.

**Comment by odahcam** [comment]
The motivation for this is to have the ability to generate avatar URLs trough script instead of HTML, so why not to export the sources instead of the factory? In that way we gotta do less work (which means less risk), users will be able to have the same ability and we won't have to deal with Source interface changes for now, that would speed up acceptance.

**Comment by PowerKiKi** [comment]
I wouldn't export source implementations, because that would open up a huge new API surface, and that would prevent us from breaking it (as we just did in the several past PRs).

Actually I would suggest to either:

- do nothing at all and let the user re-implement whatever he needs (it's mostly one liners)
- create and export a new Pipe while keeping our implementation details hidden, if it really is needed

**Comment by odahcam** [comment]
I don't mind about a new API surface, we can let users be responsible for how they use it. We could also separate the URL methods in pure functions and export just them. The Pipe idea seems nice too, but seems to be the most harder to implement.

**Pull request closed without merging**
