### PR TITLE
Feature/Angular 7 support

### LINKED ISSUE #43: Update deps. to Angular 7.0

### PR DESCRIPTION
**Pull request by odahcam**
Resolves #43

### CODE REVIEW

**Comment by HaithemMosbahi** [comment]
Hi @odahcam 
Is there any updates on this one ?

**Comment by odahcam** [comment]
I gotta test again, but maybe https://github.com/ng-packagr/ng-packagr/pull/1104 had resolved that incompatibility with `tsickle`.

**Comment by odahcam** [comment]
> but maybe ng-packagr/ng-packagr#1104 had resolved that incompatibility with tsickle.

Sorry, I mean that one: https://github.com/angular/tsickle/commit/dbe74e7f85b3df9f7eb00171ee054ec2d1996f16

**Comment by odahcam** [comment]
Looks like `tsickle` got updated, my locla build and tests have completed successfully, let's see what Travis says now!

**Comment by HaithemMosbahi** [comment]
all green :D 
great job @odahcam

**Comment by HaithemMosbahi** [comment]
@odahcam Do you confirm that this is ready to be merged and released ?

**Comment by HaithemMosbahi** [comment]
Hi @odahcam,
I think that the lib dependencies weren't updated ! we just updated the angular app that uses the library
I mean this file ./projects/ngx-avatar/package.json

**Comment by odahcam** [comment]
Wow, I didn't realised their existence, I only used CLI to upgrade everything. Travis CI should point thinks like that to us. 😢 

I take a fast look at this now.

**Comment by odahcam** [comment]
`ng update` is a liar D:

```
C:\Users\...\HaithemMosbahi\ngx-avatar\projects\ngx-avatar>ng update
    We analyzed your package.json and everything seems to be in order. Good work!
```

**Pull request merged**
