### PR TITLE
Angular 9

### PR DESCRIPTION
**Pull request by maguro**

### CODE REVIEW

**Comment by maguro** [comment]
> From what I can see only [b93ff1f](https://github.com/HaithemMosbahi/ngx-avatar/commit/b93ff1fdf0a839042f1fd893cb8bcfd47ffd4d9a) and _maybe_ [5b7af4d](https://github.com/HaithemMosbahi/ngx-avatar/commit/5b7af4ded66cd9f8b24f38ca94cafa76eb32aeb3) is really required.

iiuc, [d50bdcd](https://github.com/HaithemMosbahi/ngx-avatar/pull/85/commits/d50bdcd84f366897266e126bbf40cc0d975e9122) is needed as well.

**Comment by PowerKiKi** [comment]
I am not sure what those sha correspond to anymore. But I still see commits related to yarn on Travis that I think are not necessary.

What was the commit d50bdcd ?

**Comment by maguro** [comment]
> As a matter of fact yarn should not be used at all.
> 
> ...
> 
> This shows that npm is the preferred package manager for this project and the `yarn.lock` file must be deleted. In addition this preference should be specified for Angular CLI by adding the following in `angular.json`:
> 
> ```diff
>  {
>    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> +  "cli": {
> +    "packageManager": "npm"
> +   },
> ```

This should go into a different pull-request.  I shall file one.

**Comment by maguro** [comment]
https://github.com/HaithemMosbahi/ngx-avatar/pull/87 removes yarn.

**Comment by odahcam** [comment]
#87 is merged, you can follow with this now.

**Comment by PowerKiKi** [comment]
I took the liberty to rebase this PR in #91. Hopefully this will help to get it merged.

**Comment by odahcam** [comment]
Let's follow there then, thanks.

**Comment by maguro** [comment]
Thanks for following up on this @PowerKiKi !

**Comment by odahcam** [comment]
Thank you too for the initial PR @maguro .

**Pull request closed without merging**
