### PR TITLE
Fix for updating existing sources

### LINKED ISSUE #18: Updating the avatar based on changes happened after initial loading
I could not get the avatar updated after some changes in the user data. For example, when I load the avatar initially there is no picture which makes it falls back to initials. Later, when a profile picture is added, I need to update the avatar with that image URL. This is not happening now. 

Could anyone please help me in getting this done?

Thanks in advance.

### PR DESCRIPTION
**Pull request by haivp3010**
Fix #18

### CODE REVIEW

**Comment by mxlandry** [comment]
Can we have this fix merged soon? We have this issues in our project too. 
Thanks!
Have a nice day.

**Comment by odahcam** [comment]
I could merge, but I would still need @HaithemMosbahi to publish it to NPM anyway.

**Comment by mhosman** [comment]
Any news to publish this?

**Comment by HaithemMosbahi** [comment]
I just published a new version that should fix this issue ! I am sorry I couldn't merge this pull request because I was on the middle of doing a big refactoring to the component. 
The new version should fix this issue and I would be happy if you help to test it ! 
Thank you

**Comment by haivp3010** [comment]
> I just published a new version that should fix this issue ! I am sorry I couldn't merge this pull request because I was on the middle of doing a big refactoring to the component.
> The new version should fix this issue and I would be happy if you help to test it !
> Thank you

Thank you. That's great. So I guess we can close this pull request now right?

**Comment by odahcam** [comment]
If the issue is fixed, then yes.

**Pull request closed without merging**
