### PR TITLE
Ng6

### PR DESCRIPTION
**Pull request by sarfarazansari**
@HaithemMosbahi 
I've update library for angular 6.
I've generated code via angular-cli and removed old snippets.
tested it working fine now.

FYI
from now `demo` will be in main `src` folder
and `ngx-avatar` library will be in `projects` folder.

to make build of library we have to use `ng build --prod ngx-avatar`

and see it in action `ng serve`

let me know if you have any confusion

### CODE REVIEW

**Comment by JoeBoxr** [comment]
Hello.  Is there another location we can get this PR from and download?

**Comment by Cloud925** [comment]
any news on this PR?

**Comment by JoeBoxr** [comment]
> any news on this PR?

You can clone the latest commit of this PR and build it yourself.  That's what i did and it works fine.

**Comment by HaithemMosbahi** [comment]
Thank you for your contribution ❤️  and I'm sorry for the late reply.
I will merge your pull request to the master branch and then I will publish a new release

**Comment by HaithemMosbahi** [comment]
The next step would be fixing the build ( there's problem with running the test ) and adding a post build script to copy the readme file to the dist folder, I need it for npm documentation page.

Thanks a lot for your help in migrating the library to Angular 6

**Comment by mhosman** [comment]
Hi @HaithemMosbahi you need any help to fix this? It could be great to have this working today!

**Comment by HaithemMosbahi** [comment]
@mhosman I just released version 3.0.0. it would be great if you could test it and give me your feedback :)

**Comment by JoeBoxr** [comment]
Works great!  Thank you.

**Comment by mhosman** [comment]
@HaithemMosbahi tested and working like a charm for me!!!

**Pull request merged**
