### PR TITLE
Remove yarn

### PR DESCRIPTION
**Pull request by maguro**

### CODE REVIEW

**Comment by maguro** [comment]
Thanks!  So, what happens next?

**Comment by PowerKiKi** [comment]
keep our fingers crossed and hope for the best :crossed_fingers: :smile: 

@HaithemMosbahi, if you need help to maintain this project, have you considered adding another contributor to the project in order to merge PR ? or if you don't have interest in this project anymore, could you please inform us, so that the community can organize itself accordingly ?

**Comment by odahcam** [comment]
WHy do u want to remove yarn?

**Comment by PowerKiKi** [comment]
Because it is not used by this project. See https://github.com/HaithemMosbahi/ngx-avatar/pull/85#pullrequestreview-368498513

**Comment by odahcam** [comment]
Nice, but I can't resolve the conflicts in there, so I need @maguro to fix them so I can merge.

**Comment by PowerKiKi** [comment]
@odahcam, conflicts were resolved. Are you able to merge this now ?

**Pull request merged**
