### PR TITLE
Angular 9 (bis)

### PR DESCRIPTION
**Pull request by PowerKiKi**
This is a rebase of #85 with minor additional fixes

### CODE REVIEW

**Comment by odahcam** [comment]
Nice PR, can you confirm that you can build the lib for production?

**Comment by PowerKiKi** [comment]
I confirm that I can build the lib for production.

I am not quite sure why we don't see Travis status in this issue, but you can see it is successful over there: https://travis-ci.org/github/HaithemMosbahi/ngx-avatar/builds/674264612

Also locally the following command will also succeed (although with warnings, but I don't know if they are new or not):

```sh
ng build ngx-avatar && ng build ngx-avatar-demo
```

**Comment by odahcam** [comment]
> I am not quite sure why we don't see Travis status in this issue

Probably because it is not configured as a request for PRs and because it's travis .org not .com, so it won't work with Checks, just plain old hooks.

> I confirm that I can build the lib for production.

I wasn't able to build it in my Windows computer, but Travis is enough for me.

**Comment by PowerKiKi** [comment]
Thank you for merging.

Will you be able to release this yourself ?

According to what I see on https://www.npmjs.com/package/ngx-avatar, @HaithemMosbahi is the only collaborator for this package. It would be best to at least have a second collaborator and/or setup an auto-publish mechanism from Travis to npm.

Here is an example on how to automatically publish tags as release which should be easy to adapt for this lib. But I cannot create a PR for it since I don't know the credentials to be encoded: https://github.com/Ecodev/fab-speed-dial/blob/123e63c7faeef1d469618dcefb4a111d82fc817f/.travis.yml#L32-L47

**Comment by odahcam** [comment]
I agree with you and, unfortunately for who is in a hurry, only Haithem is able to do this for us now. Once he's back I'm pretty sure configuring a auto-publish workflow would be awesome, you could open a issue discussing that if you want, I like the idea.

**Pull request merged**
